### PR TITLE
pkg(samarium-0.3.1): Added samarium 0.3.1

### LINKED ISSUE #522: Add Samarium
It is written in Python and is installable on [PyPI](https://pypi.org/project/samarium/) as `samarium`.
GitHub Repo: https://github.com/samarium-lang/Samarium
Documentation: https://samarium-lang.github.io/Samarium

### PR DESCRIPTION
**Pull request by Endercheif**
Closes #522
- Adds Samarium as a supported language

*Accidentally deleted the branch :sob: this is a restored version fixed as mentioned*
#523

### CODE REVIEW

**Comment by Endercheif** [comment]
@HexF so sorry. I accidentally deleted the branch. But I have restored it and changed `pip3` to `pip`. :heart:

**Comment by HexF** [comment]
```
Collecting samarium==0.3.1
  Could not find a version that satisfies the requirement samarium==0.3.1 (from versions: )
No matching distribution found for samarium==0.3.1
make: *** [Makefile:21: samarium-0.3.1.pkg.tar.gz] Error 1
```

Looks like pip can't find it for some reason, would you have any ideas?

**Comment by Endercheif** [comment]
Strange, because running `pip install samarium==0.3.0` works perfectly locally. Could it be because piston cannot fetch pypi? If you see no versions even show up in this error.

**Comment by Endercheif** [comment]
I tried installing from github instead of `pypi` via `pip`, hopefully this works with the CI since it works on my machine.

**Comment by Endercheif** [comment]
Looking at the problem this time, it installs the package using `python 3.7` instead of `3.10`. Manually specifying 3.10 should fix that.

**Comment by Endercheif** [comment]
Hopefully this works. Looking at other langs that use Python, they use `bin/pip3` too

**Comment by Endercheif** [comment]
@HexF All tests finally passed!!!!

**Review by HexF — APPROVED** [review]

**Pull request merged**
