### PR TITLE
v3 - Remove the use of unshare + privileged mode

### PR DESCRIPTION
**Pull request by vfrazao-ns1**
Removes the use of unshare + privileged mode and instead uses seccomp to filter for socket syscalls. 

data/piston/config.yaml also needs to be changed to use the new config value.

Example:

```bash
$ cat test.py 
import socket
print(socket.getaddrinfo("example.org", 80, proto=socket.IPPROTO_TCP))
$ cli/index.js execute python 3.9.1 test.py
== Run ==
STDERR
    Traceback (most recent call last):
      File "/piston/jobs/4f1f95b4-1482-4bba-90ea-738e82a16fb0/test.py", line 3, in <module>
        print(socket.getaddrinfo("example.org", 80, proto=socket.IPPROTO_TCP))
      File "/piston/packages/python/3.9.1/lib/python3.9/socket.py", line 953, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -3] Temporary failure in name resolution
    
Exit Code: 1
```

### CODE REVIEW

**Comment by HexF** [comment]
Is there any way to not use a separate C program to do this - building another program within this seems a bit hacky, but other than that, I like it.

**Comment by vfrazao-ns1** [comment]
So ideas I had:
1. Use these bindings: https://github.com/roryrjb/node-seccomp and create a node program to replace the C program
2. Generate bindings for node for the current c program `nosocket.c` then have a node program that uses that

Neither ideally is super appealing to me TBH. If you have any other thoughts let me know @HexF

**Comment by HexF** [comment]
After reviewing the `node-seccomp` bindings, doesn't seem possible unless we spawn another node process - which adds more overhead.
If you wanna resolve these merge conflicts, I'll merge it in.

**Comment by vfrazao-ns1** [comment]
Merge conflict resolved, should I push a change to `data/piston/config.yaml` as well (the folder is in .gitignore)?

**Comment by HexF** [comment]
For what reason? The file is automatically generated by `api/config.js` if it does not exist.

**Comment by vfrazao-ns1** [comment]
Yeah I wasn't sure where it was coming from but locally I had to change the config option name from "enable_unshare" to "disable_networking" - I'm guessing since I had the file present already. If it's generated automatically then it should be fine.

**Comment by HexF** [comment]
Ok then it should be good to merge.

**Pull request merged**
