### PR TITLE
Remove nosocket, update docs, SIGKILL signal for timeout and output limit, output limit status

### PR DESCRIPTION
**Pull request by Brikaa**
- Removes `nosocket.c` since it is no longer used
- Updates the documentation with the new security principles
- Puts `SIGKILL` signal in the response if the submission failed due to timeout or exceeding output limits to maintain backward compatibility
- Adds response status for exceeding output limits: `EL` for stderr limit, `OL` for stdout limit.
- Mounts the package directory with its actual path inside the Isolate sandbox to account for packages that expect a `/piston/packages` directory

### CODE REVIEW

**Comment by rhlarora84** [comment]
@Brikaa I was using the docker image with the latest tag and started getting errors installing Python packages using pip3 in the /piston/packages/python/3.12.0/bin/pip3.

Errors were related to SSL "[SSLError("Can't connect to HTTPS URL because the SSL module is not available.")](https://stackoverflow.com/questions/63084049/sslerrorcant-connect-to-https-url-because-the-ssl-module-is-not-available)"

Tried an older sha tag for the Docker image from 8 months back worked fine. I can't say if this change could be related but I want to highlight it.

**Comment by Brikaa** [comment]
@rhlarora84 I will look into that. Are you using pip3 during code execution?

**Comment by Brikaa** [comment]
@rhlarora84 the problem was because the Python runtime was built using a previous version of Piston's docker image which had an older libssl library; so using the Python runtime on the newer image version caused problems. I have dowgraded the base image versions again. Let me know if there are further issues.

**Comment by rhlarora84** [comment]
Thanks for the help here

**Pull request merged**
