### PR TITLE
added the paradoc golfing language as seen on Advent of Code

### PR DESCRIPTION
**Pull request by Pyroseza**

### CODE REVIEW

**Comment by Vrganj** [comment]
Where's the paradoc test?

**Comment by Pyroseza** [comment]
> Where's the paradoc test?

An import is enough to know it’s there

**Comment by Vrganj** [comment]
You should just make it print "good" for consistency sake

**Comment by Pyroseza** [comment]
> You should just make it print "good" for consistency sake

It does....

**Comment by Pyroseza** [comment]
> > You should just make it print "good" for consistency sake
> 
> It does....

Did I forget to push... wtf

**Comment by Pyroseza** [comment]
Sorry guys, it’s there now I forgot to push that, I made the test a while back already

**Pull request merged**
