### PR TITLE
Updated the readme

### PR DESCRIPTION
**Pull request by Atharva8**
Updated the readmen to specify the new format to install specific version

### CODE REVIEW

**Comment by HexF** [comment]
Merge conflict?

**Comment by Atharva8** [comment]
I just changed `exports.command = ['install <runtimes...>'];` to `exports.command = ['install <packages...>'];` and upated the docs

**Comment by Atharva8** [comment]
Thanks!

**Comment by HexF** [comment]
I need to merge it, not just resolve the merge conflict :)

**Comment by Atharva8** [comment]
Oh sorry my bad

**Pull request merged**
