### PR TITLE
Added common lisp

### PR DESCRIPTION
**Pull request by ethancedwards8**
Added common lisp language using sbcl as compiler/interpreter, let me know if I need to change anything.

### CODE REVIEW

**Comment by Vrganj** [comment]
Looks good, mind just replacing that tab with spaces in the API?

**Comment by ethancedwards8** [comment]
Sure thing, my Vim config is unforgiving sometimes hah.

**Comment by ethancedwards8** [comment]
Bumping

**Comment by ethancedwards8** [comment]
Fixed merge conflicts

**Comment by ethancedwards8** [comment]
bumping

**Comment by realtux** [comment]
added, but pr was too old so had to rewrite a little

**Pull request closed without merging**
