### PR TITLE
#270 Install/Uninstall multiple packages using ppman

### PR DESCRIPTION
**Pull request by Atharva8**
Now ppman install can install/uninstall multiple packages in the following way:
```
cli/index.js ppman install python=3.9.4 bash=5.1.0
```

we can also install the latest version in the following way:
```
cli/index.js ppman install python bash
```

Working:
Yargs accepts multiple options in an array like this:
```['python=3.9.4', 'bash=5.1.0']```

which is split by a function which returns a key-value pair of language and version.

A loop runs through the array and send requests until all of them are installed or are failed.

### CODE REVIEW

**Review by HexF — APPROVED** [review]

**Comment by HexF** [comment]
Thanks for your contribution!

**Comment by realtux** [comment]
does this alter the way it currently works (it should not) or add an alternate syntax

**Comment by HexF** [comment]
It removed the `--language-version` flag in favor of more apt-like versioning (`language=version`)

**Comment by Atharva8** [comment]
The version should now be specified after the `=` sign with no spaces

**Comment by Atharva8** [comment]
I think I need to update the docs

**Comment by realtux** [comment]
just bear in mind people use this and we can't go breaking working stuff. getting rid of the flag is fine. is that all that changed?

**Comment by HexF** [comment]
AFAIK, yes

**Pull request merged**
