### PR TITLE
pkg(rscript-4.1.1): Added R 4.1.1

### PR DESCRIPTION
**Pull request by Brikaa**

### CODE REVIEW

**Comment by Brikaa** [comment]
The tests might fail because the Docker container needs to be updated with the dependencies

**Comment by HexF** [comment]
Maybe we try fix the builder container issue by pulling the container then running a local build, which should be fine if all layers are there, but will update if need-be.

**Comment by HexF** [comment]
^ #321 should fix it

**Comment by Brikaa** [comment]
New dependencies were installed in the API container as well, will that be okay?

**Comment by HexF** [comment]
It might fail tests then, which could be problematic

**Comment by HexF** [comment]
dc20ec2 should fix it

**Comment by Brikaa** [comment]
It will most likely fail, so re-opening

**Review by HexF — APPROVED** [review]
Looks good to me

**Comment by HexF** [comment]
some reason it wants to rebuilt because I rebased it - but its got auto-merge setup now so it should be good.
Will have to update public piston in the morning with all the updated packages

**Pull request merged**
