### PR TITLE
added requests library for fun with apis!

### PR DESCRIPTION
**Pull request by LucasLWH**
Python requests library is missing.
https://docs.python-requests.org/en/master/user/quickstart/#json-response-content
I believe this change should fix it!

Issue to replicate:
```python
import requests
import json
import random

getDogPic = requests.get('https://dog.ceo/api/breeds/image/random')
dogPic=getDogPic.json()['message']
print(dogPic)
```

Received output:
```
Traceback (most recent call last):
  File "/piston/jobs/5b200eca-dc36-4047-8cb6-a3b5293f111c/file0.code", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

### CODE REVIEW

**Comment by xjzi** [comment]
On public piston, running code can't access the internet

**Comment by LucasLWH** [comment]
Hm.. is there any workaround for this?

**Comment by ThreshMain** [comment]
> Hm.. is there any workaround for this?

You can clone the repo and host it yourself with networking enabled

**Comment by LucasLWH** [comment]
Was hoping to just be able to use the public piston, but ah well. Thanks

**Pull request closed without merging**
