### PR TITLE
pkg(pure-0.68): Add pure-lang 0.68

### PR DESCRIPTION
**Pull request by Shivansh-007**

### CODE REVIEW

**Comment by dvargas46** [comment]
couple things here to get you going further:

- on line 11 in the build script, those directories you are trying to move will not exist.
```
tar xfz llvm.tar.gz --strip-components=1        <-- --strip-components will remove the root dir of the archive
tar xfz clang.tar.gz --strip-components=1

mv clang llvm/tools/clang                       <-- therefore, "clang" and "llvm" dirs won't exist
rm llvm.tar.gz && rm clang.tar.gz
```

- I haven't looked at how to build both llvm and clang, but are you sure that this is a way to build both at the same time? I would think it'd need to be separate, but not sure.

- use SemVer on your folder structure and metadata. I think that's important for the api to detect where to go

try those out and see if it helps. then we can squash whatever issues might come after :)

**Comment by Shivansh-007** [comment]
Ok thanks @dvargas46 will try them out, one question, what is SemVer?

**Comment by Shivansh-007** [comment]
Yes, this is a way to build them correctly, I have been following this: https://agraef.github.io/pure-docs/install.html.

**Comment by HexF** [comment]
You forgot the `-O` flag on curl, so it just outputs to stdout

**Comment by dvargas46** [comment]
@Shivansh-007 try these updates:

In the build.sh script
- Change the first configure command (the one for llvm/clang) to be:
`./congure --prefix="$PREFIX" --enable-optimized --enable-targets=host-only --enable-docs="no" --enable-assertions="no"`
- Change the second configure command (the one for pure) to be:
`./configure --prefix="$PREFIX" --enable-release --with-tool-prefix="$PREFIX/bin" --with-static-llvm`

in the environment file
- Add this above the path export:
`export LD_LIBRARY_PATH=$PWD/lib`

**Pull request merged**
