### PR TITLE
Adding Raku

### PR DESCRIPTION
**Pull request by Hydrazer**

### CODE REVIEW

**Comment by HexF** [comment]
Just a few changes, can you move the languages into a version directory as like all the other packages.
You will also need to move the `v` from the version field, other than that all looks good!

Closes #281

**Comment by Hydrazer** [comment]
> Just a few changes, can you move the languages into a version directory as like all the other packages.
> You will also need to move the `v` from the version field, other than that all looks good!
> 
> Closes #281

ok I fixed it check the newest commit

**Comment by dvargas46** [comment]
one last thing, in the build script you don't need to create a bin dir at the beginning since the archive already contains a bin dir for the prebuilt binaries.

and also the semver check will complain about "6.d" because of the letter in the minor and a missing patch number. I'm not sure what makes sense to use here, but I was thinking "6.0.0-d" instead. It would capture the "d" as a prerelease.

**Comment by Hydrazer** [comment]
i changed the 6.d thing but for the first thing you mentioned do you just want me to delete the
`mkdir -p bin
cd bin/`
part?

**Comment by dvargas46** [comment]
correct. you can delete `cd ../` at the end too.

also, I just realized that the "-d" at the end of the version will cause a different issue with building and another for satisfying semver - both of which should probably be fixed if we intend to support prereleases in the future.

but for this, is there just a normal version we can use that follows the semver convention of #.#.# ?

**Comment by Hydrazer** [comment]
the only other one i could find is by using the date format for example 2021.05 or something for may 2021 but ill try looking more

**Comment by Hydrazer** [comment]
maybe i can use the ascii value of d which would be 6.100.0 or something lol

**Comment by dvargas46** [comment]
works for me

**Review by dvargas46 — APPROVED** [review]
looks good to me

**Comment by Hydrazer** [comment]
nice

**Pull request merged**
