### PR TITLE
Proposal: Add Piston Node.js Client as an Official Extension

### PR DESCRIPTION
**Pull request by dthree**
I created a [Node.js client wrapper](https://github.com/dthree/node-piston) to access the Piston API easily from Node. This makes it very easy to access the public Piston API or any private API from Node, hope you like it!

@realtux I don't mind moving this into the engineer-man account if you'd prefer that.

### CODE REVIEW

**Comment by realtux** [comment]
cool, i'll check it out. the project can stay under your account. also, did you send me an email with initials "DC"? i feel like i'm getting my names mixed up. i thought that was you but this project isn't like the one described in the email.

**Comment by dthree** [comment]
Sounds good 👍🏻 . 

Yeah, that's me. No, this isn't my bigger code playground project, but I'll be using this in it. I also am very happy with Piston so have no problem helping out the ecosystem.

I do think you would be interested in this bigger project though, so just let me know if you have some time!

**Comment by realtux** [comment]
sure, i'm not ignoring you by the way, email is still in my inbox, just haven't got around to replying.

**Comment by HexF** [comment]
I'm just looking through your code and notice the language version is specified quite unconventionally, other than that Id be happy with this as an official extension

**Comment by dthree** [comment]
@HexF You mean, like `javascript:15.0.1`, right? 

You're correct, I kind of made that up. I wanted a shorthand way to make a call without getting into specifying all the config. As you can see, the `execute()` method also supports passing in a config object, and then if you just do `execute('javascript', '...')`, it works out the most recent version for you.

Do you have a preferred syntax? If you do I dont mind updating it to that.

**Comment by HexF** [comment]
Maybe something like a chain based API?
```js
piston.runtime("javascript", "15.0.1").execute("console.log('hello world')");
```

But also give the option for 
```js
piston.execute("javascript", "15.0.1", "console.log('hello world')");
```

**Comment by dthree** [comment]
Okay, I updated it, adding a third parameter which points to all the Piston options. So:

```js
await client.execute("python", `print("Hello World");`, {
  version: "3.9.4"
});
```

**Comment by HexF** [comment]
Looks good to me

**Pull request merged**
