### PR TITLE
Nix: add python packages

### PR DESCRIPTION
**Pull request by Brikaa**

### CODE REVIEW

**Comment by HexF** [comment]
I'm gonna hold off on this for now - I am looking to implement automatic package installation but haven't had the time to get around to finding a solution.

**Comment by Brikaa** [comment]
@HexF how do you want to do that? Maybe I can give it a shot.

**Comment by HexF** [comment]
I was thinking we add a `packages` key in the nix files, which will contain the dictionary of packages supported for that runtime, e.g. with python we could just have:

```nix
{pkgs, piston, ...}:
let
    pkg = pkgs.python3;
in piston.mkRuntime {
    language = "python3";
    version = pkgs.python3.version;

    aliases = [
        "py3"
        "py"
        "python"
    ];

    run = ''
    ${pkg}/bin/python3 "$@"
    '';

    packages = pkgs.python3Packages;

    tests = [
        (piston.mkTest {
            files = {
                "test.py" = ''
                    print("OK")
                '';
            };
        })
    ];
}
```

then the packages could be automatically resolved and downloaded in another phase before compilation before being injected into the environment afterwards

**Comment by Brikaa** [comment]
Are these packages cleaned up after running?

**Comment by Brikaa** [comment]
Installing the packages separately and injecting them into the environment is a bit complicated since these packages could have dependencies. I tried installing numpy separately and putting the `site-packages` in `PYTHONPATH` but it was giving errors on importing. However, creating a ready environment with numpy seemed to work. So do you think every time a user requests some packages we should create an environment?

**Comment by Brikaa** [comment]
Actually it might be possible to install and inject. I'll look into that.

**Comment by HexF** [comment]
> Are these packages cleaned up after running?

They would only be cleaned when:
1. There are no active jobs
2. The storage used to cache these is above some threshold



> Installing the packages separately and injecting them into the environment is a bit complicated since these packages could have dependencies. I tried installing numpy separately and putting the `site-packages` in `PYTHONPATH` but it was giving errors on importing. However, creating a ready environment with numpy seemed to work. So do you think every time a user requests some packages we should create an environment?

Ideally there shouldn't need to be any special treatment for adding package support in terms of the Javascript - it should all be possible directly from the nix.

**Comment by Brikaa** [comment]
Is the user the one who defines which packages are installed or are they all installed?

**Comment by HexF** [comment]
Packages to install could be defined in the request to the `/execute` endpoint, and so it needs to be able to dynamically resolve packages.

**Pull request closed without merging**
