### PR TITLE
Fix runtime finding in v2 endpoint

### PR DESCRIPTION
**Pull request by Brikaa**

### CODE REVIEW

**Review by HexF — COMMENTED** [review]
I think it would be nice to allow some SemVer-like patterns instead of just hard-coding `*`.
Obviously we can't use actual SemVer as Nix doesn't force versions into SemVer, but maybe we can try determine the versioning scheme (e.g. CalVer, SemVer, etc.) and allow matching on them?

**Comment by Brikaa** [comment]
@HexF how about we have a configurable and changeable "mainstream" version for each package. It could be stored in some file as a package to version map or something.  Then "*" would just get this mainstream version. Other versions would be specified manually. 

This will also help solve the problem of multiple runtimes of the same package

**Comment by HexF** [comment]
@Brikaa Issue with that is we would have to pin nixpkgs to a version to ensure that all the version numbers are the same. But adding to that, what do we consider as a version from CalVer to SemVer for example?

**Comment by Brikaa** [comment]
What I mean is that we would not need to do any version comparisons or conversions. We just add a `mainstream_versions` object in the config that would include something like:
```
'python3': '3.10.4',
'bash': '5.1'
```
Choosing `*` as the version would bring this package version. Otherwise, it would see if `runtimes` has a version that matches the provided version string.

**Comment by HexF** [comment]
Ok yeah, that could work - build that map into the nix flake.

I'm thinking instead of the exact version rather it would link back to the runtime, e.g.:

```nix
{
  pistonMainstreamVersions = {
    "python3" = runtimes.python;
  };
}
```

**Comment by Brikaa** [comment]
I have got another idea. If we could somehow use an ordered data structure in `runtimes/default.nix`, we would just need to move the mainstream runtime to the top and it would take priority over other runtimes when selecting the `*` version. This can also be useful when multiple runtimes share the same aliases; the runtime that is more at the top of `default.nix` would take priority.

**Comment by HexF** [comment]
Not entirely sure if the nix-to-json conversion allows reading the order of elements in a map.

I'm using the flake to export all the available runtimes to piston, so ideally I would want to bundle all the version priority stuff into the flake.
I think a priority list would be best compared to hard-coding in runtimes for specific aliases, getting that merged in here would be great.

**Comment by Brikaa** [comment]
Should we get rid of the v3 endpoint now?

**Comment by Brikaa** [comment]
This works by loading the runtimes defined in `pistonMainstreamRuntimes` in `flake.nix` first then loading the rest of the runtimes. Choosing `*` as the version will pick the first runtime matching the request data (which will be the mainstream runtime if one is defined).

It also works with specific sets like `bash-only` and `none`.

**Review by HexF — APPROVED** [review]
Looks good!

**Pull request merged**
