### PR TITLE
Updated to `Node 18.15.0 LTS`

### PR DESCRIPTION
**Pull request by LoryPelli**
It shouldn't be a breaking change (I hope) because I'm not able to test it, so be careful when merging also if it should work

### CODE REVIEW

**Review by HexF — APPROVED** [review]

**Comment by HexF** [comment]
Line endings need to be `LF` (line feed, might be called Unix or Linux type) instead of `CRLF` (carriage-return, line feed, Windows/DOS).

**Comment by LoryPelli** [comment]
> Line endings need to be `LF` (line feed, might be called Unix or Linux type) instead of `CRLF` (carriage-return, line feed, Windows/DOS).

I don't understand if I need to change something (I'm on windows if this can help btw)

**Comment by LoryPelli** [comment]
Do you mean with SHIFT + ENTER instead of only ENTER?

**Comment by LoryPelli** [comment]
@HexF I tried using notepad++ but idk what it means...

**Review by HexF — APPROVED** [review]

**Comment by LoryPelli** [comment]
@HexF runtimes should also be updated I think

**Comment by LoryPelli** [comment]
Why it wasn't updated?
image

**Pull request merged**
