### PR TITLE
pkg(vlang-0.1.13): Add vlang 0.1.13

### LINKED ISSUE #165: Vlang Executor
See packages/ for existing examples
**Please merge to v3 branch!**

### PR DESCRIPTION
**Pull request by Shivansh-007**
Closes #165

### CODE REVIEW

**Comment by dvargas46** [comment]
SUMMARY: Set the VMODULES and TMPDIR environment vars to the current working dir in the run script.

`v run` will do a build (compile) and run. Per the `v build` help menu (remember it compiles first), it will search the @vmodules and @vlib paths (~/.vmodules and <package_location>/v/vlib  folders, respectively) to find relevant modules. But, the api runs these commands as an unprivileged user, so it cannot access/create the @vmodules directory.

In the `v build` help it says you can change the vmodule location by setting the VMODULES env var. Do that.

You will run into another issue afterwards. It will try to output and pull from /tmp, which has the same issue as above. The help page mentions this too. It respects the TMPDIR env var. Set that too, both to the current directory on run script and it should work. Those dirs will be deleted afterwards anyway on cleanup.

**Comment by dvargas46** [comment]
Also, just noticed that the git for this lang is _highly active_. This could easily introduce bugs into our builds (or anyone else's for that matter) since it is always pulling from master. I saw they had some failing builds on their end for some commits...

I'd advise you maybe checkout a specific commit that we know works and refers to a specific version of the lang. Or if they have a release download page or specific release branch, then that could work too. Just my 2 cents.

**Comment by Shivansh-007** [comment]
Thankyou dv, will try them out and let you know :D.

The paths for the two are gonna be same as `PATH` right?

**Comment by Shivansh-007** [comment]
Yes, this is a way to build them correctly, I have been following this: https://agraef.github.io/pure-docs/install.html.

**Comment by HexF** [comment]
No, in the `run` or `compile` script, you want to set the variables to PWD - you want this done at runtime and not cache it into env

**Pull request merged**
