### PR TITLE
Compile all provided files in java

### PR DESCRIPTION
**Pull request by the-codeboy**

### CODE REVIEW

**Comment by the-codeboy** [comment]
Oh ok I see now why you didn´t do this before

**Comment by the-codeboy** [comment]
Ok so my idea to fix this would be to rename the files to the correct name of the class inside. I wrote a regex to extract the name but I'm not an expert on that so I'm not sure if it always works

`(?<=public[\s\S]*(class|enum|record|interface)[\s\t]*)([^\s\t{]*)`

**Comment by the-codeboy** [comment]
Ok that won´t work due to security issues with that but it should be possible to check if the file already has the correct name and in that case compile using javac. Otherwise it could use the previously used method that only compiles a single class

**Comment by dvargas46** [comment]
We had a regex that was used in the previous version of Piston when it was using LXC still. It had similar flaws I think. You may wanna check out some of the other JVM-based langs like groovy or scala for some ideas too, but none are perfect imo.

Also, if you get it working, make sure to add it to a separate `compile` script like in other packages (checkout the [contributor's guide](https://github.com/engineer-man/piston/blob/master/packages/CONTRIBUTING.MD))

**Comment by HexF** [comment]
Closing due to inactivity. Feel free to reopen.

**Pull request closed without merging**
