### PR TITLE
packer-based lxc container building

### PR DESCRIPTION
**Pull request by HexF**
Fills the simple installation void

Possible improvement could be to use GitHub Actions to automatically build the lxc image, so that people don't spend half an hour building the LXC image. This would mean that the "advanced" installation outlined in the README would be replaced with this new packer flow, and simple could be downloading a build artifact off GitHub Actions.

### CODE REVIEW

**Comment by HexF** [comment]
On second thought, I will get the GitHub Actions flow working in the morning, it would be a much nicer installation overall.

**Comment by HexF** [comment]
That should do it, ready for a merge

**Comment by Vrganj** [comment]
I see your action errored, was that intentional?
https://github.com/HexF/piston/runs/1780899293?check_suite_focus=true

**Comment by HexF** [comment]
Oh my bad, I forgot to install LXC in the container

**Comment by HexF** [comment]
Opening new PR, as the branch no longer uses packer

**Pull request closed without merging**
